### ISSUE TITLE
[minor] Matchfinder "Team A" and "Team B" columns are inaccurate

### ISSUE THREAD

**Issue by nikodevv** [datdota/datdota#16] opened 2018-01-31 22:05 UTC
Matchfinder incorrectly categorizes teams as Team A or Team B when filtering games by the Team B input field if the Team A input field is left blank.
Notes: 
* Querying for a team in the Team A field correctly displays the searched for team as always begin in the "Team A" column of the data table.
* It looks like if the Team A field is left blank, but Team B field is filled, then the data table generated categorizes Team A as the Radiant team, and Team B as the Dire team. This is especially redundant as there is an explicit "Radiant Team" column in the data table.
 
Using EG and Luna as an example to filter down the results to only a few games (there is nothing special about EG or Luna):

Case 1 - Team A search works as intended([link to query](https://www.datdota.com/matchfinder/classic?team-a=39&heroes-a=48&patch=7.07&winner=either&after=01%2F01%2F2011&before=31%2F01%2F2018&duration=0%3B200&duration-value-from=0&duration-value-to=200&tier=1&tier=2&valve-event=does-not-matter&threshold=1)): 

1. Select Team A as EG, and filter for drafts where EG had Luna. Leave other fields blank
2. The query works as intended and the data table returned features EG as the the team in column "Team A".

Case 2 - Team B search is broken ([link to query](https://www.datdota.com/matchfinder/classic?team-b=39&heroes-b=48&patch=7.07&winner=either&after=01%2F01%2F2011&before=31%2F01%2F2018&duration=0%3B200&duration-value-from=0&duration-value-to=200&tier=1&tier=2&valve-event=does-not-matter&threshold=1))

1. Select Team B as EG, and filter for drafts where EG had Luna. Leave other fields blank
2. The same matches come up (good)
3. For all matches except the third down (match id 3595557830), EG is in the Team A column.

**Comment by Noxville** [comment] 2018-01-31 22:58
Ok, I think I know what the issue is. At first there's a SQL query to find all matches which don't break any of the filters - then once that data is taken into Groovy, there's additional processing to determine which of the sides is A and which is B (since it's possible that both sides could match both sets of heroes - for example if it were Team Cat with heroes [V, W, X, Y, Z] vs Team Dog with some other heroes; and you had Team A  = (Cat, Dog), Team A Heroes = [V, W], Team B = (Cat, Dog), Team B Heroes = [X, Y, Z]).

Somewhere in that processing - there must be a bug. I'll write some tests and try fix it tomorrow.

**Comment by Noxville** [comment] 2018-02-01 13:45
Should be fixed now - rewrote the processing pipeline. Let me know if you spot any more quirks.

I've also added a beta API version of this now live.

**Closed** 2018-02-09 23:11 UTC
